# Generated by Django 2.2.2 on 2019-06-12 08:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.IntegerField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_on', models.DateField(blank=True)),
                ('secure_proxy_ip', models.GenericIPAddressField()),
                ('unsecure_proxy_ip', models.GenericIPAddressField()),
                ('provider', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('secure_proxy_ip', models.GenericIPAddressField()),
                ('unsecure_proxy_ip', models.GenericIPAddressField()),
                ('secure_proxy_port', models.IntegerField()),
                ('unsecure_proxy_port', models.IntegerField()),
                ('threads', models.IntegerField(blank=True, default=100)),
                ('timeout', models.IntegerField(blank=True, default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurePortResult',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('secure_open_ports', models.CharField(max_length=330000)),
                ('secure_closed_ports', models.CharField(max_length=330000)),
                ('unsecure_open_ports', models.CharField(max_length=330000)),
                ('unsecure_closed_ports', models.CharField(max_length=330000)),
                ('scanned_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('secure_scan_runtime', models.CharField(max_length=255)),
                ('unsecure_scan_runtime', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenPorts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='SecuredPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secured_ports', models.CharField(max_length=260000)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenPorts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPortResult',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('open_ports', models.CharField(max_length=330000)),
                ('closed_ports', models.CharField(max_length=330000)),
                ('scanned_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('runtime', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenPorts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsecured_ports', models.CharField(max_length=260000)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenPorts.Host')),
            ],
        ),
    ]
