# Generated by Django 2.2.2 on 2019-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenPorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='schedule',
            field=models.CharField(max_length=255),
        ),
    ]
