# Generated by Django 2.2.1 on 2019-05-31 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenPorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_id',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
