# Generated by Django 2.2.1 on 2019-05-31 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenPorts', '0002_scan_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
